### PR TITLE
Fix and Update!

### PR DESCRIPTION
**Pull request by kraineff**

### CODE REVIEW

**Comment by Adaptivity** [comment]
I say "No" for lines 1 and 5

**Comment by TheVizzy** [comment]
I see Ru Thaumcraft config and Thaumium = Таум-

**Comment by ganymedes01** [comment]
Lol since I don't speak russian I'll let you guys decide whether I should merge this or not XD

**Comment by TheVizzy** [comment]
Yes! :dancer:

**Comment by TheVizzy** [comment]
Thaumium = Taum-

**Comment by Adaptivity** [comment]
@TheVizzy в некоторых модах таум, в некоторых таумическая(-ий,-ие). Нет чёткого перевода. Пускай так и останется здесь.

**Comment by Adaptivity** [comment]
@ganymedes01 ok merge this, both variants are correct but meh.

**Pull request merged**
